function calendarApp(){const year=2026,months=Array.from({length:12},(_,i)=>i+1),names=months.map(m=>m+'월');const now=new Date(),todayYear=now.getFullYear(),todayMonth=now.getMonth()+1,todayDay=now.getDate();const events={
 1:{8:['클라이언트 영상 1차 시안 마감'],12:['외주 문의 답장'],17:['성화 녹음실'],23:['세린이랑 저녁 약속'],29:['영상 수정본 전달']},
 2:{4:['브랜드 영상 촬영본 정리'],6:['2월 편집본 1차 마감'],13:['클라이언트 미팅'],18:['성화 공연'],21:['성화 녹음실'],27:['외주 영상 최종본 납품']},
 3:{5:['광고 영상 콘티 확인'],10:['편집본 1차 전달'],14:['우리 처음 만난 날'],19:['성화 공연 리허설'],24:['클라이언트 수정사항 반영'],27:['뮤직비디오 자막 수정 마감']},
 4:{3:['영상 클라이언트 미팅'],8:['인터뷰 영상 편집 마감'],15:['성화 녹음실'],19:['성화 생일 저녁'],22:['광고 영상 2차 시안'],28:['편집비 정산']},
 5:{2:['브랜드 영상 촬영본 전달'],8:['광고 영상 최종본 마감'],14:['클라이언트 미팅'],18:['성화 공연'],22:['세린이랑 점심'],26:['외주 수정본 전달'],30:['다음 프로젝트 견적 확인']},
 6:{4:['뮤직비디오 2차 편집 마감'],9:['광고 영상 촬영'],13:['클라이언트 수정사항 확인'],17:['성화 공연 보러 가기'],21:['영상 최종본 납품'],25:['성화 녹음실'],29:['편집비 정산']},
 7:{3:['여름 화보 촬영본 수령'],9:['여름 화보 편집 마감'],14:['클라이언트 미팅'],19:['성화 공연'],25:['윤호 부모님 댁 방문'],27:['광고 영상 수정본 전달'],31:['외주 견적서 발송']},
 8:{2:['브랜드 영상 1차 시안 마감'],7:['뮤직비디오 촬영본 수령'],12:['클라이언트 미팅'],16:['성화랑 휴일'],21:['광고 영상 최종본 납품'],28:['외주 수정본 전달']},
 9:{3:['클라이언트 영상 1차 시안'],8:['성화 녹음실'],15:['광고 영상 수정 마감'],20:['세린이랑 저녁 약속'],24:['세린이랑 저녁 약속'],27:{t:'자료 전달 확인',clue:'C06'},28:['영상 수정본 마감'],30:['성화 녹음실']},
 10:{1:['뮤직비디오 편집본 마감'],2:{t:'월포 일정 확인',clue:'C09'},3:['개천절'],3:['성화 공연 리허설'],4:['외주 최종본 납품'],6:['광고 영상 수정 마감'],8:['세린이랑 약속'],10:['성화 방송 녹화'],12:['편집비 정산 확인'],14:['새 프로젝트 미팅'],16:['영상 납품 마감'],20:['성화 공연'],27:['외주 영상 2차 마감'],30:['클라이언트 일정 확인']},
 11:{3:['광고 영상 납품 마감'],7:['클라이언트 미팅'],11:['성화 공연'],16:['편집본 수정 마감'],19:['외주 미팅'],26:['외주 최종본 마감']},
 12:{3:['연말 광고 영상 촬영'],5:['연말 영상 편집 마감'],12:['성화 공연'],18:['세린이랑 약속'],20:['클라이언트 최종본 납품'],24:['크리스마스'],30:['연말 정산']}
}
const monthHTML=(m,idx)=>{const first=new Date(year,m-1,1).getDay(),offset=(first+6)%7,days=new Date(year,m,0).getDate();const cells=Array(offset).fill('');for(let d=1;d<=days;d++)cells.push(String(d));while(cells.length%7)cells.push('');const weeks=[];for(let i=0;i<cells.length;i+=7)weeks.push(cells.slice(i,i+7));return`<section class="calendar-month-section" data-month="${m}" ${m===10?'data-default-month="true"':''}><div class="calendar-month-head"><div class="calendar-month">${names[idx]}</div><button class="calendar-home" data-act="home" aria-label="홈으로">➔</button></div><div class="calendar-weekdays"><span>월</span><span>화</span><span>수</span><span>목</span><span>금</span><span>토</span><span>일</span></div><div class="calendar-grid">${weeks.map((w,wi)=>`<div class="calendar-week ${wi===weeks.length-1?'last-week':''}">${w.map((d,di)=>{if(!d)return '<div class="calendar-day empty"></div>';const n=Number(d),raw=(events[m]||{})[n],list=raw?(Array.isArray(raw)?raw:[raw]):[],isToday=todayYear===year&&todayMonth===m&&todayDay===n;return `<div class="calendar-day ${isToday?'today':''} ${di>=5?'weekend':''}"><div class="calendar-number">${d}</div>${list.map(ev=>{const e=typeof ev==='string'?{t:ev}:ev;return `<button class="calendar-event ${e.clue?'calendar-clue-event':''} ${Array.from(e.t).length>5?'long':''}" data-act="caldetail" data-text="${String(e.t).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}" ${e.clue?`data-c="${e.clue}"`:''}><span class="cal-event-label">${String(e.t).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}</span></button>`}).join('')}</div>`}).join('')}</div>`).join('')}</div></section>`};return`<div class="scr app calendarapp"><div class="calendar-scroll">${months.map((m,i)=>monthHTML(m,i)).join('')}</div></div>`}
