function timeApp(){const alarms=[
 {tm:'00:10',note:'잠깐 확인'},
 {tm:'00:40',note:'자료 정리'},
 {tm:'01:20',note:'자기 전에 확인'},
 {tm:'01:50',note:'물 마시기'},
 {tm:'02:20',note:'한 번 더 확인'},
 {tm:'02:40',note:'파일 저장'},
 {tm:'03:00',note:H('C06','확인하기 · 편집하는곰'),clue:'C06'},
 {tm:'03:02',note:H('C09','위치 확인 · 월포'),clue:'C09'},
 {tm:'03:12',note:H('C08','버스 시간 확인'),clue:'C08'},
 {tm:'04:10',note:'잠들기'},
 {tm:'06:30',note:'기상'},
 {tm:'07:10',note:'준비하기'},
 {tm:'07:40',note:'알람'},
 {tm:'08:20',note:'영양제 먹기'},
 {tm:'09:00',note:'메일 확인'},
 {tm:'10:30',note:'파일 확인'},
 {tm:'11:40',note:'점심'},
 {tm:'12:10',note:'메일'},
 {tm:'13:30',note:'작업 시작'},
 {tm:'15:00',note:'잠깐 쉬기'},
 {tm:'16:20',note:'연락 확인'},
 {tm:'17:40',note:'정리하기'},
 {tm:'19:00',note:'저녁'},
 {tm:'20:30',note:'자료 백업'},
 {tm:'21:10',note:'연락하기'},
 {tm:'22:00',note:'마무리'},
 {tm:'23:10',note:'정리하기'},
 {tm:'23:50',note:'내일 일정 확인'}
];return`<div class="scr app clockapp"><div class="clock-top"><div class="clock-title">알람</div><button class="clock-home" data-act="home" aria-label="홈으로">⌂</button></div><div class="clock-body"><div class="alarm-list">${alarms.map(a=>`<button class="alarm-row ${a.clue?'alarm-clue':''}" ${a.clue?'data-act="alarmclue" data-c="'+a.clue+'"':''}><div class="alarm-main"><div class="alarm-time">${a.tm}</div><div class="alarm-note">${a.note}</div></div><span class="alarm-toggle"><i></i></span></button>`).join('')}</div></div></div>`}
